//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class gladiatorEntities : DbContext
    {
        public gladiatorEntities()
            : base("name=gladiatorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_booking> tbl_booking { get; set; }
        public virtual DbSet<tbl_flights> tbl_flights { get; set; }
        public virtual DbSet<tbl_passengers> tbl_passengers { get; set; }
        public virtual DbSet<tbl_schedules> tbl_schedules { get; set; }
        public virtual DbSet<tbl_tickets> tbl_tickets { get; set; }
        public virtual DbSet<tbl_users> tbl_users { get; set; }
    
        public virtual ObjectResult<sp_logincheck_Result> sp_logincheck(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_logincheck_Result>("sp_logincheck", usernameParameter);
        }
    
        public virtual ObjectResult<string> sp_login(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_login", usernameParameter);
        }
    
        public virtual ObjectResult<sp_getuser_Result> sp_getuser(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getuser_Result>("sp_getuser", usernameParameter);
        }
    
        public virtual int sp_updateuser(string username, string firstname, string lastname, Nullable<System.DateTime> dob, string phone)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var firstnameParameter = firstname != null ?
                new ObjectParameter("firstname", firstname) :
                new ObjectParameter("firstname", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("lastname", lastname) :
                new ObjectParameter("lastname", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_updateuser", usernameParameter, firstnameParameter, lastnameParameter, dobParameter, phoneParameter);
        }
    
        public virtual ObjectResult<sp_getpassengers_Result> sp_getpassengers(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getpassengers_Result>("sp_getpassengers", usernameParameter);
        }
    
        public virtual int sp_deletepassenger(Nullable<int> passenger_id)
        {
            var passenger_idParameter = passenger_id.HasValue ?
                new ObjectParameter("passenger_id", passenger_id) :
                new ObjectParameter("passenger_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_deletepassenger", passenger_idParameter);
        }
    
        public virtual ObjectResult<sp_getflightid_Result1> sp_getflightid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getflightid_Result1>("sp_getflightid");
        }
    
        public virtual ObjectResult<sp_getflights_Result> sp_getflights()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getflights_Result>("sp_getflights");
        }
    
        public virtual ObjectResult<sp_getschedules_Result> sp_getschedules()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getschedules_Result>("sp_getschedules");
        }
    
        public virtual ObjectResult<sp_flight_search_Result> sp_flight_search(Nullable<System.DateTime> traveldate, string src_dest, string tar_dest, Nullable<int> traveller)
        {
            var traveldateParameter = traveldate.HasValue ?
                new ObjectParameter("traveldate", traveldate) :
                new ObjectParameter("traveldate", typeof(System.DateTime));
    
            var src_destParameter = src_dest != null ?
                new ObjectParameter("src_dest", src_dest) :
                new ObjectParameter("src_dest", typeof(string));
    
            var tar_destParameter = tar_dest != null ?
                new ObjectParameter("tar_dest", tar_dest) :
                new ObjectParameter("tar_dest", typeof(string));
    
            var travellerParameter = traveller.HasValue ?
                new ObjectParameter("traveller", traveller) :
                new ObjectParameter("traveller", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_flight_search_Result>("sp_flight_search", traveldateParameter, src_destParameter, tar_destParameter, travellerParameter);
        }
    
        public virtual ObjectResult<sp_getBookedSeats_Result> sp_getBookedSeats(Nullable<int> sid)
        {
            var sidParameter = sid.HasValue ?
                new ObjectParameter("sid", sid) :
                new ObjectParameter("sid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getBookedSeats_Result>("sp_getBookedSeats", sidParameter);
        }
    
        public virtual ObjectResult<sp_get_passenger_details_Result> sp_get_passenger_details(Nullable<int> passenger_id)
        {
            var passenger_idParameter = passenger_id.HasValue ?
                new ObjectParameter("passenger_id", passenger_id) :
                new ObjectParameter("passenger_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_passenger_details_Result>("sp_get_passenger_details", passenger_idParameter);
        }
    
        public virtual ObjectResult<sp_generateticketstep1_Result> sp_generateticketstep1(Nullable<int> booking_id)
        {
            var booking_idParameter = booking_id.HasValue ?
                new ObjectParameter("booking_id", booking_id) :
                new ObjectParameter("booking_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_generateticketstep1_Result>("sp_generateticketstep1", booking_idParameter);
        }
    
        public virtual ObjectResult<sp_getBookingHistory_Result> sp_getBookingHistory(string username, string status)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getBookingHistory_Result>("sp_getBookingHistory", usernameParameter, statusParameter);
        }
    
        public virtual ObjectResult<sp_getfare_Result> sp_getfare(Nullable<int> schedule_id)
        {
            var schedule_idParameter = schedule_id.HasValue ?
                new ObjectParameter("schedule_id", schedule_id) :
                new ObjectParameter("schedule_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getfare_Result>("sp_getfare", schedule_idParameter);
        }
    }
}
