//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_schedules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_schedules()
        {
            this.tbl_booking = new HashSet<tbl_booking>();
            this.tbl_tickets = new HashSet<tbl_tickets>();
        }
    
        public int flight_id { get; set; }
        public System.DateTime travel_date { get; set; }
        public System.TimeSpan departure_time { get; set; }
        public Nullable<System.TimeSpan> arrival_time { get; set; }
        public int schedule_id { get; set; }
        public Nullable<int> avail_economy_class { get; set; }
        public Nullable<int> avail_business_class { get; set; }
        public Nullable<int> avail_first_class { get; set; }
        public Nullable<int> avail_premium_class { get; set; }
        public string schedule_status { get; set; }
        public string duration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_booking> tbl_booking { get; set; }
        public virtual tbl_flights tbl_flights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_tickets> tbl_tickets { get; set; }
    }
}
