//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tickets
    {
        public int ticket_id { get; set; }
        public string status { get; set; }
        public Nullable<int> booking_id { get; set; }
        public Nullable<System.DateTime> travel_date { get; set; }
        public Nullable<int> passenger_id { get; set; }
        public Nullable<int> gate { get; set; }
        public string seat_no { get; set; }
        public Nullable<int> schedule_id { get; set; }
    
        public virtual tbl_booking tbl_booking { get; set; }
        public virtual tbl_passengers tbl_passengers { get; set; }
        public virtual tbl_schedules tbl_schedules { get; set; }
    }
}
