//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_booking()
        {
            this.tbl_tickets = new HashSet<tbl_tickets>();
        }
    
        public int booking_id { get; set; }
        public string username { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<int> schedule_id { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_tickets> tbl_tickets { get; set; }
        public virtual tbl_schedules tbl_schedules { get; set; }
        public virtual tbl_users tbl_users { get; set; }
    }
}
