//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_flights
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_flights()
        {
            this.tbl_schedules = new HashSet<tbl_schedules>();
        }
    
        public int flight_id { get; set; }
        public string source_destination { get; set; }
        public string target_destination { get; set; }
        public Nullable<int> capacity_business_class { get; set; }
        public Nullable<int> capacity_economy_class { get; set; }
        public Nullable<int> capacity_first_class { get; set; }
        public Nullable<int> capacity_premium_class { get; set; }
        public string flight_name { get; set; }
        public Nullable<decimal> economy_class_fare { get; set; }
        public Nullable<decimal> business_class_fare { get; set; }
        public Nullable<decimal> first_class_fare { get; set; }
        public Nullable<decimal> premium_class_fare { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_schedules> tbl_schedules { get; set; }
    }
}
